steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', '-t', 
    'gcr.io/$PROJECT_ID/thingiverse-to-slant3d', 
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/thingiverse-to-slant3d']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
    'run', 
    'deploy', 
    'thingiverse-to-slant3d', 
    '--image', 
    'gcr.io/$PROJECT_ID/thingiverse-to-slant3d', 
    '--region',
    'your-region',
    '--platform',
    'managed',
    '--allow-unauthenticated',
    '--set-env-vars',
    'BUCKET_NAME=nimbus-print,GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/service-account-key.json'  # Update with your values
  ]
images:
- 'gcr.io/$PROJECT_ID/thingiverse-to-slant3d'
