steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', '-t', 
    'gcr.io/$PROJECT_ID/thingiverse-to-slant3d', 
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/thingiverse-to-slant3d']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [
    'run', 
    'deploy', 
    'thingiverse-to-slant3d', 
    '--image', 
    'gcr.io/$PROJECT_ID/thingiverse-to-slant3d', 
    '--region',
    'us-central1',  
    '--platform',
    'managed',
    '--allow-unauthenticated',
    '--set-secrets', 
    'GOOGLE_APPLICATION_CREDENTIALS=service-account-key:latest, 'THINGIVERSE_TOKEN=thingiverse-slant3d-env:latest, SLANT_API_KEY=thingiverse-slant3d-env:latest, BUCKET_NAME=thingiverse-slant3d-env:latest'  
  ]
images:
- 'gcr.io/$PROJECT_ID/thingiverse-to-slant3d'
